name: navithesia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^2.1.6
  http: ^1.3.0
  shared_preferences: ^2.0.15
  confetti: ^0.8.0
  share_plus: ^10.1.4
  path_provider: ^2.1.2
  csv: ^6.0.0
  flutter_slidable: ^4.0.0
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.1
  path: ^1.8.3

  # For local storage with Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/NT_ICON.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/NT_ICON.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/coa_schools.json
    - assets/icons/nt_icon.png
